### ISSUE TITLE
Fixed header and missed positioning

### ISSUE THREAD

**Issue by widoz** [Mango/slideout#218]
Hi, 

There is an issue for when the header or another element is positioned fixed, I think this is a css behavior as explained here Same issue here http://meyerweb.com/eric/thoughts/2011/09/12/un-fixing-fixed-elements-with-css-transforms/.

I make a copy of the page positioning the header as fixed.

here the custom css that you can find within the page:

```
<style>
    /**
     * CUSTOM STYLE FOR TESTING
     */
    .panel-header {
      position: fixed !important;
      left: 0;
      right: 0;
      width: 100% !important;
    }

    .slideout-panel {
      /**
       * Must be not set to transform or the header will not be fixed.
       */
      will-change: initial;
    }
    </style>
```

If you scroll a little and then open the menu you'll see the issue.

**Comment by pazguille** [comment]
Hi @widoz, 

I think this issue was resolved. You can read the FAQ [How to use slideout with a fixed header](https://github.com/Mango/slideout#how-to-use-slideout-with-a-fixed-header)? I worked on this issue and I found a solution for that.

If you have another issue, please let me know. If you can share a codepen link would be better.

**Comment by widoz** [comment]
Hi @pazguille,

Thank you and sorry I didn't know about the fixed header FAQ section.

By the way may be I'm doing something wrong but If I don't change the <em>will-change</em> property the header is not fixed.

You can view the test page here http://guidoscialfa.com/dev/slideout/

Also, if I set the style and copy the js code for the fixed header, scrolling down and opening the menu, the result is an header outside of the page.

I copied the code at the bottom of the page.

**Comment by pazguille** [comment]
Hi @widoz,

I see that you have to fix your markup to make it work. The header should be between of nav and main:

```html
<nav>
<header>
<main>
```
