### ISSUE TITLE
panel scrolls up when menu opens

### ISSUE THREAD

**Issue by coret** [Mango/slideout#36]
When the menu is opened this has effect on the panel: the panel "scrolls" to the top. This behaviour seems not restricted to particular devices or browsers. Especially on longer pages on touch devices, swipping to the bottom may open up the menu (when swiping a little bit to the right) and then you have to close the menu and swipe down again.

Can this behaviour be changed? I'd like the position of the panel be unchanged when the menu is opened.

**Comment by Duske** [comment]
As far as I know this is caused when **overflow: hidden** is added to the body (like in class .slideout-open). When the body changes its overflow css property, the page jumps to the top.

**Comment by pazguille** [comment]
This issue was resolved on #21. Could you please test it again? https://mango.github.io/slideout/

**Comment by coret** [comment]
Thanks, removing the **overflow:hidden** does indeed solve this issue.

May be update the CSS example on https://mango.github.io/slideout/ and file https://github.com/Mango/slideout/blob/master/index.css where the **overflow:hidden** is still present?

**Comment by pazguille** [comment]
The fix was:
- Remove width and height 100% from `html`.
- Add `overflow:hidden` to `.slideout-panel` when the slideout is opened.

I'm going to update the CSS example on demo page.

:)

**Comment by phillipadsmith** [comment]
@pazguille Doesn't look like the CSS changes are reflected in the README or demo page.

**Comment by nickmeagher** [comment]
@pazguille That worked for me! Thank you.
